# Generated by Django 3.1.5 on 2021-01-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210110_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Dia do nascimento'),
        ),
    ]
