# Generated by Django 3.1.5 on 2021-01-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='primeiro_nome',
            field=models.CharField(default='a', max_length=50, verbose_name='Primeiro nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listener',
            name='sobrenome',
            field=models.CharField(default='a', max_length=50, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
    ]
