# Generated by Django 3.1.5 on 2021-01-27 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210127_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seguido', to='accounts.artist', verbose_name='Artista')),
                ('ouvinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seguidor', to='accounts.listener', verbose_name='Ouvinte')),
            ],
            options={
                'verbose_name': 'Segue',
                'verbose_name_plural': 'Seguem',
            },
        ),
    ]
