# Generated by Django 3.1.5 on 2021-01-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_segue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome artistico'),
        ),
    ]
