# Generated by Django 3.1.5 on 2021-01-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210129_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numero de Telefone'),
        ),
    ]
