# Generated by Django 3.1.5 on 2021-01-27 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_segue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da musica')),
                ('duracao', models.IntegerField(verbose_name='Duração da musica')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musicas',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da musica')),
                ('enumeração', models.BooleanField(verbose_name='enumeração')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
            },
        ),
        migrations.CreateModel(
            name='Grava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Artista', to='accounts.artist', verbose_name='artista')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Musica', to='musica.musica', verbose_name='Musica')),
            ],
            options={
                'verbose_name': 'Curte',
                'verbose_name_plural': 'Curtem',
            },
        ),
        migrations.CreateModel(
            name='Curte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seguidor', to='musica.musica', verbose_name='Musica')),
                ('ouvinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Curto', to='accounts.listener', verbose_name='Ouvinte')),
            ],
            options={
                'verbose_name': 'Curte',
                'verbose_name_plural': 'Curtem',
            },
        ),
        migrations.CreateModel(
            name='Cria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateField(verbose_name='Data de criação')),
                ('ouvinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criador', to='accounts.listener', verbose_name='Ouvinte')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criada', to='musica.playlist', verbose_name='Playlist')),
            ],
            options={
                'verbose_name': 'Cria',
                'verbose_name_plural': 'Criadas',
            },
        ),
    ]
