# Generated by Django 3.1.5 on 2021-01-28 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grava',
            options={'verbose_name': 'Grava', 'verbose_name_plural': 'Gravam'},
        ),
        migrations.RemoveField(
            model_name='cria',
            name='ouvinte',
        ),
        migrations.AddField(
            model_name='cria',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criador', to='accounts.user', verbose_name='Ouvinte'),
            preserve_default=False,
        ),
    ]
