# Generated by Django 3.1.5 on 2021-01-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_auto_20210128_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cria',
            name='playlist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criada', to='musica.playlist', verbose_name='Playlist'),
        ),
    ]
