# Generated by Django 3.1.5 on 2021-01-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_auto_20210129_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cria',
            name='data_de_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
    ]
